create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  year integer not null,
  brief text not null,
  description text,
  role text,
  status text,
  tech_stack text[] not null default '{}',
  features text[] not null default '{}',
  challenges text[] not null default '{}',
  lessons text,
  image_paths text[] not null default '{}',
  github_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  title text not null,
  description text[] not null default '{}',
  start_date date not null,
  end_date date,
  image_paths text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tracker_games (
  id bigint generated by default as identity primary key,
  title text not null,
  year integer not null,
  pity_std_num integer not null,
  pity_std_max integer not null,
  pity_lim_num integer not null,
  pity_lim_max integer not null,
  guaranteed_lim boolean not null default false,
  pity_wep_num integer not null,
  pity_wep_max integer not null,
  guaranteed_wep boolean not null default false,
  banner_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_projects_updated_at on public.projects;
create trigger set_projects_updated_at
before update on public.projects
for each row
execute function public.set_updated_at();

drop trigger if exists set_articles_updated_at on public.articles;
create trigger set_articles_updated_at
before update on public.articles
for each row
execute function public.set_updated_at();

drop trigger if exists set_tracker_games_updated_at on public.tracker_games;
create trigger set_tracker_games_updated_at
before update on public.tracker_games
for each row
execute function public.set_updated_at();